CREATE DATABASE SISTEMA_EMPRESARIAL;
USE SISTEMA_EMPRESARIAL;

CREATE TABLE DEPARTAMENTOS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(200) NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL
)ENGINE=INNODB;

CREATE TABLE REUNIOES(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATA DATE NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
    DEPARTAMENTO_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS(ID)
)ENGINE=INNODB;

CREATE TABLE FUNCIONARIOS(
	ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    SENHA CHAR(32) NOT NULL,
    DEPARTAMENTOS_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(DEPARTAMENTOS_ID) REFERENCES DEPARTAMENTOS(ID)
)ENGINE=INNODB;

INSERT INTO DEPARTAMENTOS
VALUES(NULL,"Administração","");
INSERT INTO DEPARTAMENTOS
VALUES(NULL,"Contabilidade","");
INSERT INTO DEPARTAMENTOS
VALUES(NULL,"Recursos humanos","");
INSERT INTO DEPARTAMENTOS
VALUES(NULL,"TI","");
INSERT INTO DEPARTAMENTOS
VALUES(NULL,"Manutenção","");
 
drop table REUNIOES;
 
 select* from FUNCIONARIOS where EMAIL = 'ana@gamil.com' and SENHA= '1234';


